### ISSUE TITLE
cannot set prespawn on sumo

### ISSUE THREAD

**Issue by vincyxiroff** [gFabri/Hosts-FREE#1]
[18:34:09 INFO]: vincyxirttv issued server command: /host arena prespawn Sumo
[18:34:09 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'host' in plugin Host v1.5
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.8.8.jar:git-PandaSpigot-107]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched_1.8.8.jar:git-PandaSpigot-107]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:700) ~[patched_1.8.8.jar:git-PandaSpigot-107]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1213) ~[patched_1.8.8.jar:git-PandaSpigot-107]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1025) ~[patched_1.8.8.jar:git-PandaSpigot-107]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.8.8.jar:git-PandaSpigot-107]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.8.8.jar:git-PandaSpigot-107]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(PlayerConnectionUtils.java:9) ~[patched_1.8.8.jar:git-PandaSpigot-107]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_312]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_312]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:11) ~[patched_1.8.8.jar:git-PandaSpigot-107]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:881) ~[patched_1.8.8.jar:git-PandaSpigot-107]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:412) ~[patched_1.8.8.jar:git-PandaSpigot-107]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:815) ~[patched_1.8.8.jar:git-PandaSpigot-107]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:648) ~[patched_1.8.8.jar:git-PandaSpigot-107]
        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:133) ~[patched_1.8.8.jar:git-PandaSpigot-107]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
        at com.github.bfabri.hosts.utils.Cuboid.<init>(Cuboid.java:63) ~[?:?]
        at com.github.bfabri.hosts.commands.arena.arguments.PreSpawnArgument.onCommand(PreSpawnArgument.java:36) ~[?:?]
        at com.github.bfabri.hosts.commands.arena.ArenaExecutor.onCommand(ArenaExecutor.java:52) ~[?:?]
        at com.github.bfabri.hosts.commands.host.HostExecutor.onCommand(HostExecutor.java:54) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.8.8.jar:git-PandaSpigot-107]
        ... 16 more

**Comment by gFabri** [comment]
fixed, check in release, see if it works fine.
